---

- name: Install sshpass, this is required for Ansible ssh connection via password
  yum:
    name: sshpass
    state: present
- name: Ensure public key for current User exists
  stat:
    path: ~/.ssh/id_rsa.pub
- name: Ensure inventory hosts are not present in known hosts
  known_hosts:
    name: "{{ hostvars[item]['ansible_host'] }}"
    state: absent
  loop: "{{ groups.all }}"
- name: Get ssh key of inventory hosts
  command:
    cmd: "ssh-keyscan -H {{ hostvars[item]['ansible_host'] }}"
  changed_when: false
  loop: "{{ groups.all }}"
  register: keyscan
- name: Add current ssh key of inventory hosts to known hosts
  known_hosts:
    name: "{{ hostvars[item.item]['ansible_host'] }}"
    key: "{{ hostvars[item.item]['ansible_host'] }} {{ item.stdout_lines.0.split(' ')[1] }} {{ item.stdout_lines.0.split(' ')[2] }}"
    hash_host: yes
    state: present
  loop: "{{ keyscan.results }}"
  loop_control:
    label: "{{ item.item }}"
