---

- name: Install sshpass, this is required for Ansible ssh connection via password
  package:
    name: sshpass
    state: present

- name: Ensure public key for current User exists
  stat:
    path: ~/.ssh/id_rsa.pub

- name: Get ssh key of inventory hosts
  command:
    cmd: "ssh-keyscan -H {{ hostvars[item]['ansible_host'] }}"
  changed_when: false
  loop: "{{ groups.all }}"
  register: keyscan

# IDEE: momentan hinterlegter Key mit akutellen Keys vergleichen, falls Key vorhanden, muss er nicht ausgetauscht werden
#- name: Get ssh key for inventory hosts from known hosts
#  command:
#    cmd: "ssh-keygen -F {{ hostvars[item]['ansible_host'] }}"
#  changed_when: false
#  loop: "{{ groups.all }}"
#  register: known_hosts_ssh_keys

#- name: Show current ssh key of every inventory host
#  debug: 
#    msg: "{{ item.stdout | regex_replace('(.*\\n.*\\s)(.*)', '\\2') }}"
#  loop: "{{ known_hosts_ssh_keys.results }}"
#  loop_control:
#    label: "{{ item.item }}"
#- debug:
#    msg: "{{ item.stdout_lines | regex_replace('(.*\\n.*\\s)(.*)', '\\2') }}"
#  loop: "{{ keyscan.results }}"
#  loop_control:
#    label: "{{ item.item }}"

#- debug:
#    msg: "Key vorhanden"
#  loop: known_hosts_ssh_keys
#  when: 

- name: Remove ssh key for inventory hosts as it might not be the current one
  known_hosts:
    path: "{{ ansible_facts['user_dir'] }}/.ssh/known_hosts"
    name: "{{ hostvars[item]['ansible_host'] }}"
    state: absent
  loop: "{{ groups.all }}"

- name: Add current ssh key of inventory hosts to known hosts
  known_hosts:
    path: "{{ ansible_facts['user_dir'] }}/.ssh/known_hosts"
    name: "{{ hostvars[item.item]['ansible_host'] }}"
    key: "{{ hostvars[item.item]['ansible_host'] }} {{ item.stdout_lines.0.split(' ')[1] }} {{ item.stdout_lines.0.split(' ')[2] }}"
    hash_host: yes
    state: present
  loop: "{{ keyscan.results }}"
  loop_control:
    label: "{{ item.item }}"
