---

- name: Prepare localhost
  hosts: localhost
  connection: local
  roles:
    - management

- name: Prepare Raspberry Pi Cluster nodes
  hosts: rpi
  become: true
  pre_tasks:
    - name: Ensure playbook is running against Raspberry Pi hosts
      ansible.builtin.assert:
        that:
          - ansible_architecture == "aarch64"
          - ansible_kernel is search(".*rpi.*")
        quiet: true
        fail_msg: Target host is not a Raspberry Pi, check your inventory!
  roles:
    - rpi_ansible
