---

- name: Update all packages # noqa package-latest
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Assert if (Debian-based) host needs rebooting
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists
  when: ansible_facts['os_family'] == "Debian"
  notify: Reboot_handler

# - name: Set hostname
#   ansible.builtin.hostname:
#     name: "{{ inventory_hostname }}"

# - name: Install yum utils
#   ansible.builtin.yum:
#     name: yum-utils
#     state: present

# - name: Assert if host needs rebooting
#   ansible.builtin.command:
#     cmd: needs-restarting -r
#   failed_when: reboot_required.rc == 2
#   changed_when: reboot_required.rc != 0
#   register: reboot_required
#   notify: Reboot_handler
