---

- name: Create User for further Ansible automation
  ansible.builtin.user:
    name: "{{ rpi_ansible_automation_user }}"
    comment: "User for Ansible automation tasks"

- name: Enable sudo permissions for Ansible user
  ansible.builtin.copy:
    content: "{{ rpi_ansible_automation_user }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/ansible
    validate: /usr/sbin/visudo -cf %s
    mode: "0644"

# Playbook currently connects to target hosts via password
- name: Ensure public key for current User exists
  ansible.builtin.stat:
    path: ~/.ssh/id_rsa.pub
  delegate_to: localhost
  become: false

- name: Add public key of current User to authorized_keys of Ansible User
  ansible.posix.authorized_key:
    user: "{{ rpi_ansible_automation_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
