---

- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Install yum utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Assert if host needs rebooting
  ansible.builtin.command:
    cmd: needs-restarting -r
  failed_when: reboot_required.rc == 2
  changed_when: reboot_required.rc != 0
  register: reboot_required
  notify: reboot
