---
# After initial installation of CentOS image the SD card is not fully utilized.
# These tasks extend the root partition to use all of the available space

- name: Assert if root partition needs to get expanded
  command: "growpart {{ ansible_cmdline.root | regex_replace('\\^(\/dev\/)(?P<device>.*)(p)(?P<devicenumber>.)\\$', '/dev/\\g<device> \\g<devicenumber>') }} -N"
  failed_when: false
  changed_when: false
  register: partition_needs_resizing

- name: Expand root partition
  command: /usr/bin/rootfs-expand
  register: rootfs_expand_status
  failed_when: "'CHANGED' not in rootfs_expand_status.stdout"
  when: "'NOCHANGE' not in partition_needs_resizing.stdout"
